//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DM.App.Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AKLPositions
    {
        public int AKLPositionId { get; set; }
        public string AKLPositionCode { get; set; }
        public string AKLPositionDescription { get; set; }
        public bool AKLPositionIsActive { get; set; }
    }
}
