//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DM.App.Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Antliostasia
    {
        public int AntliostasioId { get; set; }
        public string AntliostasioCode { get; set; }
        public string AntliostasioDescription { get; set; }
        public bool AntliostasioIsActive { get; set; }
        public string AntliostasioOnomasia { get; set; }
        public string AntliostasioAddress { get; set; }
        public string AntliostasioThesi { get; set; }
        public Nullable<int> AntliostasioTypeId { get; set; }
        public string AntliostasioTypeDescription { get; set; }
        public int AntliostasioSectorId { get; set; }
    }
}
