//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DM.App.Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categories
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Categories()
        {
            this.CategoriesFields = new HashSet<CategoriesFields>();
            this.CategoriesFieldsPerApplicationRole = new HashSet<CategoriesFieldsPerApplicationRole>();
            this.CategoriesFieldsPerTaskType = new HashSet<CategoriesFieldsPerTaskType>();
            this.CategoriesRoles = new HashSet<CategoriesRoles>();
        }
    
        public int Id { get; set; }
        public string CategoryName { get; set; }
        public Nullable<int> ParentCategoryId { get; set; }
        public bool AllowNew { get; set; }
        public bool AllowView { get; set; }
        public string Alias { get; set; }
        public string JSUrl { get; set; }
        public int RowStatus { get; set; }
        public System.DateTime RowInserted { get; set; }
        public System.DateTime RowLastUpdated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoriesFields> CategoriesFields { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoriesFieldsPerApplicationRole> CategoriesFieldsPerApplicationRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoriesFieldsPerTaskType> CategoriesFieldsPerTaskType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoriesRoles> CategoriesRoles { get; set; }
    }
}
