//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DM.App.Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentsToTasks
    {
        public System.Guid ID { get; set; }
        public int DepartmentId { get; set; }
        public int TaskId { get; set; }
        public int SectorID { get; set; }
        public int IsActive { get; set; }
    }
}
