//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DM.App.Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dexamenes
    {
        public int DexameniID { get; set; }
        public string ScadaCode { get; set; }
        public string DexameniName { get; set; }
        public string Perioxi { get; set; }
        public string Address { get; set; }
        public string Ypsometro { get; set; }
        public Nullable<decimal> Capacity { get; set; }
        public Nullable<int> SectorId { get; set; }
    }
}
