//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DM.App.Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncidentsRouting
    {
        public int RecId { get; set; }
        public string ComesFromTTDeptName { get; set; }
        public int RouteToDepartmentId { get; set; }
        public bool RoutingIsActive { get; set; }
        public string ComesFromTTSectorName { get; set; }
        public string ProblemD04Description { get; set; }
        public System.DateTime FromWorkingDate { get; set; }
        public System.DateTime ToWorkingDate { get; set; }
        public System.DateTime FromWeekendDate { get; set; }
        public System.DateTime ToWeekendDate { get; set; }
    }
}
