//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DM.App.Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incidents
    {
        public System.Guid TT_Id { get; set; }
        public string ID1022 { get; set; }
        public string Customer_Name { get; set; }
        public string Customer_Phone { get; set; }
        public string Customer_Email { get; set; }
        public string Municipality { get; set; }
        public string Street_Name { get; set; }
        public string Street_Number { get; set; }
        public string Comments { get; set; }
        public int Sector { get; set; }
        public string Perioxi { get; set; }
        public string TaxKodikas { get; set; }
        public Nullable<int> TmimaID { get; set; }
        public string TmimaName { get; set; }
        public Nullable<System.DateTime> HmerominiaAnagelias { get; set; }
        public Nullable<System.DateTime> OraAnagelias { get; set; }
        public string OnomaKalountos { get; set; }
        public string OnomaKatanaloti { get; set; }
        public Nullable<int> EidosProblimatosID { get; set; }
        public string EidosProblimatosDescr { get; set; }
        public Nullable<int> ProblimaId { get; set; }
        public string ProblimaDescr { get; set; }
        public string ArithmosMitroou { get; set; }
        public string ArithmosMetriti { get; set; }
        public string ArithmosLogariasmou { get; set; }
        public Nullable<decimal> SyntetagmenesVlavis_GeogrMikos { get; set; }
        public Nullable<decimal> SyntetagmenesVlavis_GeogrPlatos { get; set; }
        public Nullable<int> AitiaID { get; set; }
        public string AitiaDescr { get; set; }
        public string RelatedID1022 { get; set; }
        public string Orofos { get; set; }
        public string Diadromi { get; set; }
        public Nullable<int> EksypiretisiID { get; set; }
        public string EksypiretisiDescr { get; set; }
        public string KodikosKtiriou { get; set; }
        public Nullable<int> TyposXrisisID { get; set; }
        public string TyposXrisisDescr { get; set; }
        public Nullable<int> EgkatastasiID { get; set; }
        public string EgkatastasiDescr { get; set; }
        public string TEBCC { get; set; }
        public Nullable<int> SourceId { get; set; }
        public string SourceDescr { get; set; }
        public Nullable<int> KodikosZonisPiesis { get; set; }
        public string OnomasiaZonisPiesis { get; set; }
        public Nullable<int> KodikosApomonosis { get; set; }
        public string Position { get; set; }
        public Nullable<int> KrisimotitaID { get; set; }
        public string KrisimotitaDescr { get; set; }
        public Nullable<System.DateTime> HmerominiaEidopoiisis { get; set; }
        public Nullable<System.DateTime> OraEidopoiisis { get; set; }
        public Nullable<System.DateTime> HmerominiaApostolis { get; set; }
        public Nullable<int> HmeresApomonosis { get; set; }
        public string UserID { get; set; }
        public int Status { get; set; }
        public string BCC_ArithmosAitimatos { get; set; }
        public string BCC_CustomerCode { get; set; }
        public string BCC_TyposTE { get; set; }
        public string BCC_DescriptionTE { get; set; }
        public string BCC_StatusTE { get; set; }
        public Nullable<System.DateTime> BCC_HmerominiaEnarxisTE { get; set; }
        public Nullable<System.DateTime> BCC_HmerominiaAnathesisTE { get; set; }
        public Nullable<System.DateTime> BCC_HmerominiaOloklirosis { get; set; }
        public Nullable<System.DateTime> BCC_HmerominiaTeleutaiasEnimerosisTE { get; set; }
        public string BCC_AnatethikeSeID { get; set; }
        public string BCC_AnatethikeSeName { get; set; }
        public string BCC_Question { get; set; }
        public string BCC_Answer { get; set; }
        public string Odos2 { get; set; }
        public string Odos3 { get; set; }
        public Nullable<System.DateTime> DateOfRegistry { get; set; }
        public string BCC_Remarks { get; set; }
        public Nullable<System.DateTime> ClosingDate { get; set; }
        public string TicketTraceId { get; set; }
        public string RoutingPath { get; set; }
        public Nullable<int> Propagated_toberemoved { get; set; }
        public string BackEndTabletId_toberemoved { get; set; }
    }
}
