//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DM.App.Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Investigations
    {
        public System.Guid InvestigationsId { get; set; }
        public string FakelosId { get; set; }
        public string Fakelos_Municipality { get; set; }
        public string Fakelos_Odos { get; set; }
        public string Fakelos_Perioxi { get; set; }
        public string Fakelos_Arithmos { get; set; }
        public string Tupos_sumbantos { get; set; }
        public string Anaggelia_Sumb_Kwdikos { get; set; }
        public Nullable<System.DateTime> Anaggelia_Sumb_Hmerominia { get; set; }
        public Nullable<System.DateTime> Anaggelia_Sumb_Ora { get; set; }
        public Nullable<bool> Anaggelia_Sumb_Epelifthi_Purosbestiki { get; set; }
        public Nullable<bool> Anaggelia_Sumb_Epelifthi_Ellas { get; set; }
        public Nullable<bool> Anaggelia_Sumb_Epelifthi_Allo { get; set; }
        public string Anaggelia_Sumb_Tomeas { get; set; }
        public string Dieuthinsi_Sumb_Odos { get; set; }
        public string Dieuthinsi_Sumb_Arithmos { get; set; }
        public string Dieuthinsi_Sumb_Perioxi { get; set; }
        public string Dieuthinsi_Sumb_TK { get; set; }
        public string SynergeioEpemvasis_1 { get; set; }
        public string SynergeioEpemvasis_2 { get; set; }
        public Nullable<bool> Apokatastasi_Blabis { get; set; }
        public Nullable<System.DateTime> Apokatastasi_Blabis_Hmerominia { get; set; }
        public Nullable<System.DateTime> Apokatastasi_Blabis_Ora_Enarxis { get; set; }
        public Nullable<System.DateTime> Apokatastasi_Blabis_Ora_Lixis { get; set; }
        public string Apokatastasi_Blabis_Energeies_Sunerg { get; set; }
        public string Aitio_Eidos_Zimias { get; set; }
        public string Zimwthentes_1_Onoma { get; set; }
        public string Zimwthentes_1_Dieuthinsi { get; set; }
        public string Zimwthentes_1_ThlStathero { get; set; }
        public string Zimwthentes_1_ThlKinito { get; set; }
        public string Zimwthentes_1_Email { get; set; }
        public Nullable<bool> Zimwthentes_1_Idioktitis { get; set; }
        public Nullable<bool> Zimwthentes_1_Enoikiastis { get; set; }
        public string Zimwthentes_2_Onoma { get; set; }
        public string Zimwthentes_2_Dieuthinsi { get; set; }
        public string Zimwthentes_2_ThlStathero { get; set; }
        public string Zimwthentes_2_ThlKinito { get; set; }
        public string Zimwthentes_2_Email { get; set; }
        public Nullable<bool> Zimwthentes_2_Idioktitis { get; set; }
        public Nullable<bool> Zimwthentes_2_Enoikiastis { get; set; }
        public string Euthini_Tritwn { get; set; }
        public string Perigrafi_Zimiwn { get; set; }
        public string Aporipsi_zimiwmenwn { get; set; }
        public Nullable<bool> Idiotiki_Asfalisi { get; set; }
        public string Idiotiki_Asfalisi_Etairia { get; set; }
        public string StoixeiaEpisynaptomena_FileAttachments { get; set; }
        public string Paratiriseis { get; set; }
        public string Inv_Onoma { get; set; }
        public string Inv_AM { get; set; }
        public string Inv_Thlefwno { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string ID1022 { get; set; }
        public Nullable<int> SectorId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
    }
}
