//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DM.App.Library.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExternalDBEntities : DbContext
    {
        public ExternalDBEntities()
            : base("name=ExternalDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<CategoriesFields> CategoriesFields { get; set; }
        public virtual DbSet<CategoriesFieldsPerApplicationRole> CategoriesFieldsPerApplicationRole { get; set; }
        public virtual DbSet<CategoriesFieldsPerTaskType> CategoriesFieldsPerTaskType { get; set; }
        public virtual DbSet<CategoriesRoles> CategoriesRoles { get; set; }
        public virtual DbSet<DataSourceTypes> DataSourceTypes { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<DepartmentsToTasks> DepartmentsToTasks { get; set; }
        public virtual DbSet<Fields> Fields { get; set; }
        public virtual DbSet<FieldStates> FieldStates { get; set; }
        public virtual DbSet<Incidents> Incidents { get; set; }
        public virtual DbSet<IncidentsRouting> IncidentsRouting { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Sectors> Sectors { get; set; }
        public virtual DbSet<Tasks> Tasks { get; set; }
        public virtual DbSet<TaskTypes> TaskTypes { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<VisitCrew> VisitCrew { get; set; }
        public virtual DbSet<VisitEquipment> VisitEquipment { get; set; }
        public virtual DbSet<vCategoriesHierarchy> vCategoriesHierarchy { get; set; }
        public virtual DbSet<Personnel> Personnel { get; set; }
        public virtual DbSet<Vehicles> Vehicles { get; set; }
        public virtual DbSet<C_VLAVESATH_TAitia> C_VLAVESATH_TAitia { get; set; }
        public virtual DbSet<C_VLAVESATH_TEidos> C_VLAVESATH_TEidos { get; set; }
        public virtual DbSet<C_VLAVESATH_TWay> C_VLAVESATH_TWay { get; set; }
        public virtual DbSet<AKLPositions> AKLPositions { get; set; }
        public virtual DbSet<Antliostasia> Antliostasia { get; set; }
        public virtual DbSet<VehicleTypes> VehicleTypes { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<RoutingHistory> RoutingHistory { get; set; }
        public virtual DbSet<StatusDefinitions> StatusDefinitions { get; set; }
        public virtual DbSet<Dexamenes> Dexamenes { get; set; }
        public virtual DbSet<D04> D04 { get; set; }
        public virtual DbSet<AitiaProblimatonPiesis> AitiaProblimatonPiesis { get; set; }
        public virtual DbSet<Investigations> Investigations { get; set; }
        public virtual DbSet<Visits> Visits { get; set; }
    }
}
