//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DM.App.Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoutingHistory
    {
        public System.Guid TTId { get; set; }
        public int SectorId { get; set; }
        public int DepartmentId { get; set; }
        public System.DateTime RouteDate { get; set; }
        public Nullable<int> FromDepartmentId { get; set; }
    }
}
