//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DM.App.Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        public System.Guid Task_Id { get; set; }
        public string Task_Description { get; set; }
        public string Comments { get; set; }
        public string State { get; set; }
        public int TaskTypeId { get; set; }
        public System.Guid Incident_Id { get; set; }
        public int SectorId { get; set; }
        public int DepartmentId { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> ClosingDate { get; set; }
        public Nullable<int> Propagated { get; set; }
        public string BackEndTabletId { get; set; }
        public string LastUserName { get; set; }
    
        public virtual TaskTypes TaskTypes { get; set; }
    }
}
