//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DM.App.Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public int SectorId { get; set; }
        public int DepartmentId { get; set; }
        public int RoleId { get; set; }
        public string UserEmail { get; set; }
        public int IsActive { get; set; }
        public int AM { get; set; }
        public string Name { get; set; }
        public string SurName { get; set; }
        public string UserNameBCC { get; set; }
        public bool AccessToInvestigations { get; set; }
        public string Layout { get; set; }
    }
}
