//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DM.App.Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicles
    {
        public int VehicleID { get; set; }
        public int VehicleSector { get; set; }
        public int VehicleDepartment { get; set; }
        public string VehicleRegNumber { get; set; }
        public int VehicleType { get; set; }
        public Nullable<bool> IsEydap { get; set; }
        public string OwnerName { get; set; }
        public string OwnerSurName { get; set; }
    }
}
