//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace EydapTickets.gr.eydap.dominosrv2 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DominoSoapBinding", Namespace="urn:TTUpdate")]
    public partial class TTUpdateService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback UPDATEDRAINSTTOperationCompleted;
        
        private System.Threading.SendOrPostCallback UPDATEWATERSUPPLYTTOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TTUpdateService() {
            this.Url = global::EydapTickets.Properties.Settings.Default.EydapTicketsPortal_gr_eydap_dominosrv2_TTUpdateService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event UPDATEDRAINSTTCompletedEventHandler UPDATEDRAINSTTCompleted;
        
        /// <remarks/>
        public event UPDATEWATERSUPPLYTTCompletedEventHandler UPDATEWATERSUPPLYTTCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:TTUpdate", ResponseNamespace="urn:TTUpdate")]
        [return: System.Xml.Serialization.SoapElementAttribute("UPDATEDRAINSTTReturn")]
        public RESPONSE UPDATEDRAINSTT(string TICKETTRACEID, string STATUS, string COMPLETIONDATE, string COMMENTS) {
            object[] results = this.Invoke("UPDATEDRAINSTT", new object[] {
                        TICKETTRACEID,
                        STATUS,
                        COMPLETIONDATE,
                        COMMENTS});
            return ((RESPONSE)(results[0]));
        }
        
        /// <remarks/>
        public void UPDATEDRAINSTTAsync(string TICKETTRACEID, string STATUS, string COMPLETIONDATE, string COMMENTS) {
            this.UPDATEDRAINSTTAsync(TICKETTRACEID, STATUS, COMPLETIONDATE, COMMENTS, null);
        }
        
        /// <remarks/>
        public void UPDATEDRAINSTTAsync(string TICKETTRACEID, string STATUS, string COMPLETIONDATE, string COMMENTS, object userState) {
            if ((this.UPDATEDRAINSTTOperationCompleted == null)) {
                this.UPDATEDRAINSTTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUPDATEDRAINSTTOperationCompleted);
            }
            this.InvokeAsync("UPDATEDRAINSTT", new object[] {
                        TICKETTRACEID,
                        STATUS,
                        COMPLETIONDATE,
                        COMMENTS}, this.UPDATEDRAINSTTOperationCompleted, userState);
        }
        
        private void OnUPDATEDRAINSTTOperationCompleted(object arg) {
            if ((this.UPDATEDRAINSTTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UPDATEDRAINSTTCompleted(this, new UPDATEDRAINSTTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:TTUpdate", ResponseNamespace="urn:TTUpdate")]
        [return: System.Xml.Serialization.SoapElementAttribute("UPDATEWATERSUPPLYTTReturn")]
        public RESPONSE UPDATEWATERSUPPLYTT(string TICKETTRACEID, string STATUS, string COMPLETIONDATE, string COMMENTS) {
            object[] results = this.Invoke("UPDATEWATERSUPPLYTT", new object[] {
                        TICKETTRACEID,
                        STATUS,
                        COMPLETIONDATE,
                        COMMENTS});
            return ((RESPONSE)(results[0]));
        }
        
        /// <remarks/>
        public void UPDATEWATERSUPPLYTTAsync(string TICKETTRACEID, string STATUS, string COMPLETIONDATE, string COMMENTS) {
            this.UPDATEWATERSUPPLYTTAsync(TICKETTRACEID, STATUS, COMPLETIONDATE, COMMENTS, null);
        }
        
        /// <remarks/>
        public void UPDATEWATERSUPPLYTTAsync(string TICKETTRACEID, string STATUS, string COMPLETIONDATE, string COMMENTS, object userState) {
            if ((this.UPDATEWATERSUPPLYTTOperationCompleted == null)) {
                this.UPDATEWATERSUPPLYTTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUPDATEWATERSUPPLYTTOperationCompleted);
            }
            this.InvokeAsync("UPDATEWATERSUPPLYTT", new object[] {
                        TICKETTRACEID,
                        STATUS,
                        COMPLETIONDATE,
                        COMMENTS}, this.UPDATEWATERSUPPLYTTOperationCompleted, userState);
        }
        
        private void OnUPDATEWATERSUPPLYTTOperationCompleted(object arg) {
            if ((this.UPDATEWATERSUPPLYTTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UPDATEWATERSUPPLYTTCompleted(this, new UPDATEWATERSUPPLYTTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:TTUpdate")]
    public partial class RESPONSE {
        
        private bool sUCCESSField;
        
        private string rEASONField;
        
        private string eRRORTYPEField;
        
        private string eRRORCODEField;
        
        /// <remarks/>
        public bool SUCCESS {
            get {
                return this.sUCCESSField;
            }
            set {
                this.sUCCESSField = value;
            }
        }
        
        /// <remarks/>
        public string REASON {
            get {
                return this.rEASONField;
            }
            set {
                this.rEASONField = value;
            }
        }
        
        /// <remarks/>
        public string ERRORTYPE {
            get {
                return this.eRRORTYPEField;
            }
            set {
                this.eRRORTYPEField = value;
            }
        }
        
        /// <remarks/>
        public string ERRORCODE {
            get {
                return this.eRRORCODEField;
            }
            set {
                this.eRRORCODEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void UPDATEDRAINSTTCompletedEventHandler(object sender, UPDATEDRAINSTTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UPDATEDRAINSTTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UPDATEDRAINSTTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RESPONSE Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RESPONSE)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void UPDATEWATERSUPPLYTTCompletedEventHandler(object sender, UPDATEWATERSUPPLYTTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UPDATEWATERSUPPLYTTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UPDATEWATERSUPPLYTTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RESPONSE Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RESPONSE)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591