//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EydapTickets.ServiceReferenceGIS {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:eydap1022")]
    public partial class FaultsMessageFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string faultCodeField;
        
        private string faultDescriptionField;
        
        private long faultIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string FaultCode {
            get {
                return this.faultCodeField;
            }
            set {
                this.faultCodeField = value;
                this.RaisePropertyChanged("FaultCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string FaultDescription {
            get {
                return this.faultDescriptionField;
            }
            set {
                this.faultDescriptionField = value;
                this.RaisePropertyChanged("FaultDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long FaultID {
            get {
                return this.faultIDField;
            }
            set {
                this.faultIDField = value;
                this.RaisePropertyChanged("FaultID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:eydap1022", ConfigurationName="ServiceReferenceGIS.eydap1022PortType")]
    public interface eydap1022PortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="getMunicipalities", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EydapTickets.ServiceReferenceGIS.FaultsMessageFault), Action="getMunicipalities", Name="FaultsMessageFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        EydapTickets.ServiceReferenceGIS.getMunicipalitiesResponse1 getMunicipalities(EydapTickets.ServiceReferenceGIS.getMunicipalitiesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getStreets", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EydapTickets.ServiceReferenceGIS.FaultsMessageFault), Action="getStreets", Name="FaultsMessageFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        EydapTickets.ServiceReferenceGIS.getStreetsResponse getStreets(EydapTickets.ServiceReferenceGIS.getStreetsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getAddressCoordinate", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EydapTickets.ServiceReferenceGIS.FaultsMessageFault), Action="getAddressCoordinate", Name="FaultsMessageFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        EydapTickets.ServiceReferenceGIS.getAddressCoordinateResponse getAddressCoordinate(EydapTickets.ServiceReferenceGIS.getAddressCoordinateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getCrossCoordinate", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EydapTickets.ServiceReferenceGIS.FaultsMessageFault), Action="getCrossCoordinate", Name="FaultsMessageFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        EydapTickets.ServiceReferenceGIS.getCrossCoordinateResponse getCrossCoordinate(EydapTickets.ServiceReferenceGIS.getCrossCoordinateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getWaterDetails", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EydapTickets.ServiceReferenceGIS.FaultsMessageFault), Action="getWaterDetails", Name="FaultsMessageFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        EydapTickets.ServiceReferenceGIS.getWaterDetailsResponse getWaterDetails(EydapTickets.ServiceReferenceGIS.getWaterDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getDepartments", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EydapTickets.ServiceReferenceGIS.FaultsMessageFault), Action="getDepartments", Name="FaultsMessageFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        EydapTickets.ServiceReferenceGIS.getDepartmentsResponse getDepartments(EydapTickets.ServiceReferenceGIS.getDepartmentsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:eydap1022")]
    public partial class getMunicipalitiesResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] municipalitiesListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("municipality", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] municipalitiesList {
            get {
                return this.municipalitiesListField;
            }
            set {
                this.municipalitiesListField = value;
                this.RaisePropertyChanged("municipalitiesList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMunicipalitiesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMunicipalitiesRequest", Namespace="urn:eydap1022", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public object getMunicipalitiesRequest1;
        
        public getMunicipalitiesRequest() {
        }
        
        public getMunicipalitiesRequest(object getMunicipalitiesRequest1) {
            this.getMunicipalitiesRequest1 = getMunicipalitiesRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMunicipalitiesResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:eydap1022", Order=0)]
        public EydapTickets.ServiceReferenceGIS.getMunicipalitiesResponse getMunicipalitiesResponse;
        
        public getMunicipalitiesResponse1() {
        }
        
        public getMunicipalitiesResponse1(EydapTickets.ServiceReferenceGIS.getMunicipalitiesResponse getMunicipalitiesResponse) {
            this.getMunicipalitiesResponse = getMunicipalitiesResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStreetsRequest", WrapperNamespace="urn:eydap1022", IsWrapped=true)]
    public partial class getStreetsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:eydap1022", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string municipality_name;
        
        public getStreetsRequest() {
        }
        
        public getStreetsRequest(string municipality_name) {
            this.municipality_name = municipality_name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStreetsResponse", WrapperNamespace="urn:eydap1022", IsWrapped=true)]
    public partial class getStreetsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:eydap1022", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("street", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] streetsList;
        
        public getStreetsResponse() {
        }
        
        public getStreetsResponse(string[] streetsList) {
            this.streetsList = streetsList;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:eydap1022")]
    public partial class getAddressCoordinateResponseCoordinate : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string municipalityField;
        
        private string tkField;
        
        private string districtField;
        
        private string streetField;
        
        private string numberField;
        
        private string longitudeField;
        
        private string latitudeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string municipality {
            get {
                return this.municipalityField;
            }
            set {
                this.municipalityField = value;
                this.RaisePropertyChanged("municipality");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string tk {
            get {
                return this.tkField;
            }
            set {
                this.tkField = value;
                this.RaisePropertyChanged("tk");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string district {
            get {
                return this.districtField;
            }
            set {
                this.districtField = value;
                this.RaisePropertyChanged("district");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
                this.RaisePropertyChanged("street");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("latitude");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAddressCoordinateRequest", WrapperNamespace="urn:eydap1022", IsWrapped=true)]
    public partial class getAddressCoordinateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:eydap1022", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string municipality;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:eydap1022", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string street;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:eydap1022", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string number;
        
        public getAddressCoordinateRequest() {
        }
        
        public getAddressCoordinateRequest(string municipality, string street, string number) {
            this.municipality = municipality;
            this.street = street;
            this.number = number;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAddressCoordinateResponse", WrapperNamespace="urn:eydap1022", IsWrapped=true)]
    public partial class getAddressCoordinateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:eydap1022", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("coordinate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EydapTickets.ServiceReferenceGIS.getAddressCoordinateResponseCoordinate[] coordinateList;
        
        public getAddressCoordinateResponse() {
        }
        
        public getAddressCoordinateResponse(EydapTickets.ServiceReferenceGIS.getAddressCoordinateResponseCoordinate[] coordinateList) {
            this.coordinateList = coordinateList;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:eydap1022")]
    public partial class getCrossCoordinateResponseCoordinate : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string municipalityField;
        
        private string tkField;
        
        private string districtField;
        
        private string street1Field;
        
        private string street2Field;
        
        private string longitudeField;
        
        private string latitudeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string municipality {
            get {
                return this.municipalityField;
            }
            set {
                this.municipalityField = value;
                this.RaisePropertyChanged("municipality");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string tk {
            get {
                return this.tkField;
            }
            set {
                this.tkField = value;
                this.RaisePropertyChanged("tk");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string district {
            get {
                return this.districtField;
            }
            set {
                this.districtField = value;
                this.RaisePropertyChanged("district");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string street1 {
            get {
                return this.street1Field;
            }
            set {
                this.street1Field = value;
                this.RaisePropertyChanged("street1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string street2 {
            get {
                return this.street2Field;
            }
            set {
                this.street2Field = value;
                this.RaisePropertyChanged("street2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("latitude");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCrossCoordinateRequest", WrapperNamespace="urn:eydap1022", IsWrapped=true)]
    public partial class getCrossCoordinateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:eydap1022", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string municipality;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:eydap1022", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string street1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:eydap1022", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string street2;
        
        public getCrossCoordinateRequest() {
        }
        
        public getCrossCoordinateRequest(string municipality, string street1, string street2) {
            this.municipality = municipality;
            this.street1 = street1;
            this.street2 = street2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCrossCoordinateResponse", WrapperNamespace="urn:eydap1022", IsWrapped=true)]
    public partial class getCrossCoordinateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:eydap1022", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("coordinate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EydapTickets.ServiceReferenceGIS.getCrossCoordinateResponseCoordinate[] coordinateList;
        
        public getCrossCoordinateResponse() {
        }
        
        public getCrossCoordinateResponse(EydapTickets.ServiceReferenceGIS.getCrossCoordinateResponseCoordinate[] coordinateList) {
            this.coordinateList = coordinateList;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:eydap1022")]
    public partial class getWaterDetailsResponseInside_isolation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string isolationField;
        
        private propertyType[] isolation_propertyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string isolation {
            get {
                return this.isolationField;
            }
            set {
                this.isolationField = value;
                this.RaisePropertyChanged("isolation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("isolation_property", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public propertyType[] isolation_property {
            get {
                return this.isolation_propertyField;
            }
            set {
                this.isolation_propertyField = value;
                this.RaisePropertyChanged("isolation_property");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:eydap1022")]
    public partial class propertyType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string property_nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string property_name {
            get {
                return this.property_nameField;
            }
            set {
                this.property_nameField = value;
                this.RaisePropertyChanged("property_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getWaterDetailsRequest", WrapperNamespace="urn:eydap1022", IsWrapped=true)]
    public partial class getWaterDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:eydap1022", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string longitude;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:eydap1022", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string latitude;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:eydap1022", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string isolation_last_days;
        
        public getWaterDetailsRequest() {
        }
        
        public getWaterDetailsRequest(string longitude, string latitude, string isolation_last_days) {
            this.longitude = longitude;
            this.latitude = latitude;
            this.isolation_last_days = isolation_last_days;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getWaterDetailsResponse", WrapperNamespace="urn:eydap1022", IsWrapped=true)]
    public partial class getWaterDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:eydap1022", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pressure_zone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:eydap1022", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EydapTickets.ServiceReferenceGIS.getWaterDetailsResponseInside_isolation inside_isolation;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:eydap1022", Order=2)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("isolation", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("isolation_property", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false, NestingLevel=1)]
        public EydapTickets.ServiceReferenceGIS.propertyType[][] near_isolations;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:eydap1022", Order=3)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("valve", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("valve_property", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false, NestingLevel=1)]
        public EydapTickets.ServiceReferenceGIS.propertyType[][] near_fault_valves;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:eydap1022", Order=4)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("isolation", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("isolation_property", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false, NestingLevel=1)]
        public EydapTickets.ServiceReferenceGIS.propertyType[][] last_isolations;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:eydap1022", Order=5)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("alarm", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("alarm_property", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false, NestingLevel=1)]
        public EydapTickets.ServiceReferenceGIS.propertyType[][] last_alarms;
        
        public getWaterDetailsResponse() {
        }
        
        public getWaterDetailsResponse(string pressure_zone, EydapTickets.ServiceReferenceGIS.getWaterDetailsResponseInside_isolation inside_isolation, EydapTickets.ServiceReferenceGIS.propertyType[][] near_isolations, EydapTickets.ServiceReferenceGIS.propertyType[][] near_fault_valves, EydapTickets.ServiceReferenceGIS.propertyType[][] last_isolations, EydapTickets.ServiceReferenceGIS.propertyType[][] last_alarms) {
            this.pressure_zone = pressure_zone;
            this.inside_isolation = inside_isolation;
            this.near_isolations = near_isolations;
            this.near_fault_valves = near_fault_valves;
            this.last_isolations = last_isolations;
            this.last_alarms = last_alarms;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDepartmentsRequest", WrapperNamespace="urn:eydap1022", IsWrapped=true)]
    public partial class getDepartmentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:eydap1022", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string longitude;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:eydap1022", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string latitude;
        
        public getDepartmentsRequest() {
        }
        
        public getDepartmentsRequest(string longitude, string latitude) {
            this.longitude = longitude;
            this.latitude = latitude;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDepartmentsResponse", WrapperNamespace="urn:eydap1022", IsWrapped=true)]
    public partial class getDepartmentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:eydap1022", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string waterDepartment;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:eydap1022", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sewDepartment;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:eydap1022", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pkEydap;
        
        public getDepartmentsResponse() {
        }
        
        public getDepartmentsResponse(string waterDepartment, string sewDepartment, string pkEydap) {
            this.waterDepartment = waterDepartment;
            this.sewDepartment = sewDepartment;
            this.pkEydap = pkEydap;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface eydap1022PortTypeChannel : EydapTickets.ServiceReferenceGIS.eydap1022PortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class eydap1022PortTypeClient : System.ServiceModel.ClientBase<EydapTickets.ServiceReferenceGIS.eydap1022PortType>, EydapTickets.ServiceReferenceGIS.eydap1022PortType {
        
        public eydap1022PortTypeClient() {
        }
        
        public eydap1022PortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public eydap1022PortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public eydap1022PortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public eydap1022PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EydapTickets.ServiceReferenceGIS.getMunicipalitiesResponse1 getMunicipalities(EydapTickets.ServiceReferenceGIS.getMunicipalitiesRequest request) {
            return base.Channel.getMunicipalities(request);
        }
        
        public EydapTickets.ServiceReferenceGIS.getStreetsResponse getStreets(EydapTickets.ServiceReferenceGIS.getStreetsRequest request) {
            return base.Channel.getStreets(request);
        }
        
        public EydapTickets.ServiceReferenceGIS.getAddressCoordinateResponse getAddressCoordinate(EydapTickets.ServiceReferenceGIS.getAddressCoordinateRequest request) {
            return base.Channel.getAddressCoordinate(request);
        }
        
        public EydapTickets.ServiceReferenceGIS.getCrossCoordinateResponse getCrossCoordinate(EydapTickets.ServiceReferenceGIS.getCrossCoordinateRequest request) {
            return base.Channel.getCrossCoordinate(request);
        }
        
        public EydapTickets.ServiceReferenceGIS.getWaterDetailsResponse getWaterDetails(EydapTickets.ServiceReferenceGIS.getWaterDetailsRequest request) {
            return base.Channel.getWaterDetails(request);
        }
        
        public EydapTickets.ServiceReferenceGIS.getDepartmentsResponse getDepartments(EydapTickets.ServiceReferenceGIS.getDepartmentsRequest request) {
            return base.Channel.getDepartments(request);
        }
    }
}
